{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "policy-management.server" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "policy-management.server" . }}
type: Opaque
data:
  DB_PASSWORD: {{ $depServices.rds.password | b64enc | quote }}
