apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  secret.yaml: |

    #redis服务
    redis:
      connectInfo:
        username: {{.Values.depServices.redis.connectInfo.username | quote }}
        password: {{.Values.depServices.redis.connectInfo.password | quote }}
        sentinelUsername: {{.Values.depServices.redis.connectInfo.sentinelUsername | quote }}
        sentinelPassword: {{.Values.depServices.redis.connectInfo.sentinelPassword | quote }}
