{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mount-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  secret.conf: |

    [cluster]
    db_user : {{ $depServices.rds.user }}
    db_password : {{ $depServices.rds.password }}
