{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # REISD密码
  REDIS_USER: {{ $depServices.redis.connectInfo.username | b64enc | quote }}
  REDIS_PASSWORD: {{ $depServices.redis.connectInfo.password  | b64enc | quote }}
  REDIS_SENTINEL_USER: {{ $depServices.redis.connectInfo.sentinelUsername | b64enc | quote }}
  REDIS_SENTINEL_PASSWORD: {{ $depServices.redis.connectInfo.sentinelPassword  | b64enc | quote }}
