{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
{{- if .Values.components.ecronManagement.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dataflow.ecronManagement.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  cronsvr-secret.yaml: |
    #数据库
    db_addr: {{ $depServices.rds.host | quote }}
    db_port: {{ $depServices.rds.port }}
    user_name: {{ $depServices.rds.user | quote }}
    user_pwd: {{ $depServices.rds.password | quote }}
    db_name: {{ $depServices.rds.database | quote }}
    system_id: {{ $depServices.rds.system_id | quote }}
    db_format: {{ $depServices.rds.dbFormat | default "utf8" | quote }}
    max_open_conns: {{ $depServices.rds.maxConnections | default 30 }}
    timeout: {{ $depServices.rds.timeout | default 10 }}
    read_timeout: {{ $depServices.rds.readTimeout | default 10 }}
    write_timeout: {{ $depServices.rds.writeTimeout | default 10 }}
{{- end }}
