{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  secret.yaml: |

    # 数据库
    db_host: {{ $depServices.rds.host | quote }}
    db_port: {{ $depServices.rds.port }}
    user_name: {{ $depServices.rds.user | quote }}
    user_pwd: {{ $depServices.rds.password | quote }}
    db_name: {{ $depServices.rds.database | quote }}
    db_charset: {{ $depServices.rds.dbCharset | quote }}

    #redis服务
    redis:
      connectInfo:
        username: {{$depServices.redis.connectInfo.username | quote }}
        password: {{$depServices.redis.connectInfo.password | quote }}
        sentinelUsername: {{$depServices.redis.connectInfo.sentinelUsername | quote }}
        sentinelPassword: {{$depServices.redis.connectInfo.sentinelPassword | quote }}
