apiVersion: v1
appVersion: 0.4.0-22e93c8-20260313.6
description: A Helm authorization service chart for Kubernetes
keywords:
- authorization
- IdentifyAndAuthentication
name: authorization
version: 0.4.0-22e93c8-20260313.6
