{{- if .Values.service.AgentExecutor.ingress.enabled -}}
{{ if .Values.service.AgentExecutor.ingress.interface }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.moduleName }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500M"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
{{- $ingressClassName := include "mergedGlobalValues.ingressClassName" . -}}
{{- if $ingressClassName }}
  ingressClassName: {{ include "mergedGlobalValues.ingressClassName" . }}
{{- end }}
  rules:
  - http:
      paths:
        {{- range .Values.service.AgentExecutor.ingress.interface.path }}
        - path: {{ . }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $.Values.moduleName }}
              port:
                number: {{ $.Values.service.AgentExecutor.port }}
        {{- end }}
{{ end }}
{{- end }}
