apiVersion: v1
appVersion: 1.0.0
description: A Helm sharemgnt-single service chart for Kubernetes
keywords:
- sharemgnt-single
- InformationSecurityFabric
name: sharemgnt-single
version: 0.4.0-d9444a8-20260313.1
