{{- $env := include "mergedGlobalValues.env" . | fromYaml -}}
{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.moduleName }}
  namespace: {{ .Release.Namespace }}
stringData:
  # 配置文件路径/sysvol/conf/agent-retrieval-secret.yaml
  agent-retrieval-secret.yaml: |
    redis:
      connectInfo:
        username: {{$depServices.redis.connectInfo.username | quote }}
        password: {{$depServices.redis.connectInfo.password | quote }}
        host: {{$depServices.redis.connectInfo.host | quote }}
        port: {{$depServices.redis.connectInfo.port }}
        masterHost: {{$depServices.redis.connectInfo.masterHost | quote }}
        masterPort: {{$depServices.redis.connectInfo.masterPort }}
        slaveHost: {{$depServices.redis.connectInfo.slaveHost | quote }}
        slavePort: {{$depServices.redis.connectInfo.slavePort }}
        sentinelHost: {{$depServices.redis.connectInfo.sentinelHost | quote }}
        sentinelPort: {{$depServices.redis.connectInfo.sentinelPort }}
        sentinelUsername: {{$depServices.redis.connectInfo.sentinelUsername | quote }}
        sentinelPassword: {{$depServices.redis.connectInfo.sentinelPassword | quote }}
        masterGroupName: {{$depServices.redis.connectInfo.masterGroupName | quote }}
