replicaCount: 1
namespace: dip
moduleName: agent-executor
image:
  registry: ""
  repository: dip/agent-executor
  repositoryJob: /dip/agent-executor-job
  tag: 0.1.0-release-decision-agent-0.1.0.git-fb10cc2
  pullPolicy: IfNotPresent
  name: agent-executor
service:
  ingressclassname: ""
  AgentExecutor:
    type: ClusterIP
    port: 30778
    nodePort: 31022
    enableDolphinAgentVerbose: false
    logLevel: info
    debugMode: false
    isPrintLastCommitInfo: false
    logConversationSessionInit: false
    isWriteExceptionLogToFile: false
    ingress:
      enabled: true
      interface:
        path:
          - /api/agent-executor/v1
  enableDualStack: false
  type: ClusterIP
  ports:
    port1: 30778
    protocol1: TCP
    targetPort1: 30778
    name1: agent-executor
  telemetry:
    log:
      enabled: false
      endpoint: "http://127.0.0.1"
    metric:
      enabled: false
      endpoint: "http://127.0.0.1"
    trace:
      enabled: false
      endpoint: "http://127.0.0.1"
  enableSensitiveWordDetection: false
  doNotUseExploreBlockV2: false
  disableDolphinSdkLLMCache: false
  useContextEngineerV2: true
  enableDolphinAgentOutputVariablesCtrl: true
  isSkillAgentNeedProgress: false
resources:
  requests:
    cpu: 0.01
    memory: 1Gi
  limits:
    cpu: 11
    memory: 20Gi
probe:
  livenessProbe:
    httpGet:
      path: /api/agent-executor/v1/health/alive
      port: 30778
    initialDelaySeconds: 25
    periodSeconds: 50
    timeoutSeconds: 20
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/agent-executor/v1/health/ready
      port: 30778
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  startupProbe:
    httpGet:
      path: /api/agent-executor/v1/health/ready
      port: 30778
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
nodeSelector: {}
depServices:
  rds:
    host: "rds-proton-rds-mariadb-cluster"
    port: "3320"
    user: "anydata"
    password: "your-rds-password-here"
    type: ""
    database: "anydata"
    maxConnections: 5
  redis:
    connectType: sentinel
    enableSSL: false
    connectInfo:
      sentinelHost: kg-redis-cluster-proton-redis-sentinel
      sentinelPort: 26379
      username: root
      password: your-redis-password-here
      sentinelUsername: root
      sentinelPassword: your-redis-sentinel-password-here
      masterGroupName: mymaster
      masterHost: your-redis-master-host
      masterPort: 26379
      slaveHost: your-redis-slave-host
      slavePort: 26379
      host: ""
      port: 26379
    secretName: redis-ssl-secret
    caName: ca.pem
    certName: cert.pem
    keyName: key.pem
  llm_ad:
    embeddingUrl: ""
    embeddingDimension: 768
  rerank_ad:
    rerankUrl: ""
  opensearch:
    read: "opensearch-read"
    write: "opensearch-write"
    host: "opensearch-master"
    port: "9200"
    user: "admin"
    password: "your-opensearch-password-here"
  graphDatabase:
    type: "nebulaGraph"
    host: "kg-nebula-cluster-proton-nebula-graphd"
    port: "9669"
    user: "root"
    password: "nebula"
    readonlyuser: "anydata"
    readonlypassword: "your-nebula-readonly-password-here"
enableSystemLog: true
rps:
  limit: 100 #每秒最大请求数
