{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  secret.yaml: |

    #数据库
    user_name: {{ $depServices.rds.user | quote }}
    user_pwd: {{ $depServices.rds.password | quote }}
    db_name: {{ $depServices.rds.database | quote }}
    db_charset: {{ $depServices.rds.dbCharset | quote }}
