{{- $env := include "mergedGlobalValues.env" . | fromYaml -}}
{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dataflowtools.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "coderunner.fullname" . }}
{{ include "coderunner.labels" . | indent 4 }}
data:
  DB_PASSWORD: {{ $depServices.rds.password | toString | b64enc | quote }}
  REDIS_USERNAME: {{ $depServices.redis.connectInfo.username | b64enc | quote }}
  REDIS_PASSWORD: {{ $depServices.redis.connectInfo.password | toString | b64enc | quote }}
  REDIS_SENTINEL_USERNAME:  {{ $depServices.redis.connectInfo.sentinelUsername | b64enc | quote }}
  REDIS_SENTINEL_PASSWORD:  {{ $depServices.redis.connectInfo.sentinelPassword| toString | b64enc | quote }}