{{- $env := include "mergedGlobalValues.env" . | fromYaml -}}
{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.moduleName }}
  namespace: {{ .Release.Namespace }}
stringData:
  # 配置文件路径/sysvol/conf/agent-operator-app-secret.yaml
  agent-operator-app-secret.yaml: |
    db:
      host: {{ $depServices.rds.host | quote }}
      port: {{ $depServices.rds.port }}
      user_name: {{$depServices.rds.user | quote }}
      password: {{$depServices.rds.password | quote }}
      db_name: {{ $depServices.rds.database | quote }}
      charset: {{ $depServices.rds.dbCharset | quote }}

    opensearch:
      host: {{ $depServices.opensearch.host | quote }}
      port: {{ $depServices.opensearch.port }}
      protocol: {{ $depServices.opensearch.protocol }}
      user: {{ $depServices.opensearch.user | quote }}
      password: {{ $depServices.opensearch.password | quote }}
      version: {{ $depServices.opensearch.version }}
