apiVersion: v1
appVersion: 0.4.0-5e5bab4-20260313.9
description: A Helm user-management service chart for Kubernetes
keywords:
- user-management
- InformationSecurityFabric
name: user-management
version: 0.4.0-5e5bab4-20260313.9
