{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
{{- $rds := $depServices.rds -}}
{{- $dbReadHost := $rds.hostRead | default $rds.host | default $rds.readHost -}}
{{- $dbReadPort := $rds.portRead | default $rds.port | default $rds.readPort -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  cluster.conf: |

    [cluster]
{{- if contains "," $rds.host }}
    db_host = DM
{{- else}}
    db_host = {{ $rds.host }}
{{- end}}
    db_port = {{ $rds.port }}
    db_user = {{ $rds.user }}
    db_password = {{ $rds.password }}
    use_external_db = False
    enable_db_read = {{ $rds.enableDBRead }}
    db_read_host = {{ $dbReadHost }}
    db_read_port = {{ $dbReadPort }}
    db_type = {{ $rds.type }}
