{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret-env
  namespace: {{ .Release.Namespace }}
stringData:
  DB_PASSWORD: {{ $depServices.rds.password | quote }}
