{{- $env := include "mergedGlobalValues.env" . | fromYaml -}}
{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
{{- $accessAddress := include "mergedGlobalValues.accessAddress" . | fromYaml -}}
{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.moduleName }}-cm
  namespace: {{ .Release.Namespace }}
data:
  ontology-query-config.yaml: |
    server:
      {{- toYaml .Values.config.server | nindent 6 }}
    log:
      {{- toYaml .Values.config.log | nindent 6 }}
    observability:
      {{- toYaml .Values.config.observability | nindent 6 }}
    depServices: 
      {{- toYaml $depServices | nindent 6 }}
