{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
{{- if .Values.components.streamDataPipeline.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.streamDataPipeline.moduleName }}-cm
  namespace: {{ .Release.Namespace }}
data:
  pipeline-config.yaml: |
    server:
      {{- toYaml .Values.streamDataPipeline.config.server | nindent 6 }}
    log:
      {{- toYaml .Values.streamDataPipeline.config.log | nindent 6 }}
    kafka:
      {{- toYaml .Values.streamDataPipeline.config.kafka | nindent 6 }}
    depServices:
      authorization-private:
        host: {{ $depServices.authorization.privateHost }}
        port: {{ $depServices.authorization.privatePort }}
        protocol: http
      flow-stream-data-pipeline:
        host: {{ index $depServices "flow-stream-data-pipeline" "host" }}
        port: {{ index $depServices "flow-stream-data-pipeline" "port" }}
        protocol: {{ index $depServices "flow-stream-data-pipeline" "protocol" }}
      hydra-admin:
        host: {{ $depServices.hydra.administrativeHost }}
        port: {{ $depServices.hydra.administrativePort }}
        protocol: {{ $depServices.hydra.administrativeProtocol }}
      index-base:
        host: {{ index $depServices "index-base" "host" }}
        port: {{ index $depServices "index-base" "port" }}
        protocol: {{ index $depServices "index-base" "protocol" }}
      mq:
        {{- toYaml $depServices.mq | nindent 8 }}
      opensearch:
        {{- toYaml $depServices.opensearch | nindent 8 }}
      rds:
        {{- toYaml $depServices.rds | nindent 8 }}

  dm_svc.conf: |
    TIME_ZON=(480)
    LANGUAGE=(cn)
    DM=({{ $depServices.rds.host }})
    [DM]
    LOGIN_MODE=(1)
{{- end }}
