{{- $env := include "mergedGlobalValues.env" . | fromYaml -}}
{{- $depServices := include "mergedGlobalValues.depServices" . | fromYaml -}}
{{- $accessAddress := include "mergedGlobalValues.accessAddress" . | fromYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-yaml
  namespace: {{ .Release.Namespace }}
data:
  message.yaml: |

    # 配置文件路径/sysvol/conf/message.yaml
    lang: {{ .Values.service.language | quote }} #系统语言

    # Message服务
    svc_host: 0.0.0.0
    svc_public_port: {{ .Values.service.port }}
    svc_private_port: {{ add1 .Values.service.port }}
    mq_host: {{ .Values.depServices.mq.mqHost | quote }}
    mq_port: {{ .Values.depServices.mq.mqPort }}
    mq_lookupd_host: {{ .Values.depServices.mq.mqLookupdHost | quote }}
    mq_lookupd_port: {{ .Values.depServices.mq.mqLookupdPort }}
    mq_connector_type: {{ .Values.depServices.mq.connectorType | quote }}
    business_time_offset: {{ .Values.service.businessTimeOffset }}
    to_do_msg_clean_time : {{ .Values.service.todoMsgCleanTime }}
    notification_msg_clean_time : {{ .Values.service.notificationCleanTime }}
    invalid_msg_clean_time : {{ .Values.service.invalidMsgCleanTime }}
    log_level: {{ .Values.service.logLevel }}
    user_management_private_host: {{ index .Values.depServices "user-management" "privateHost" | quote }}
    user_management_private_port: {{ index .Values.depServices "user-management" "privatePort" }}

    # 数据库
    db_host: {{ .Values.depServices.rds.host | quote }}
    db_port: {{ .Values.depServices.rds.port }}
    max_open_conns: {{ .Values.depServices.rds.maxConnections }}
    db_host_read: ""
    db_port_read: 0
    max_open_read_conns: 20
    timeout: {{ .Values.depServices.rds.timeout }}
    read_timeout: {{ .Values.depServices.rds.readTimeout }}
    write_timeout: {{ .Values.depServices.rds.writeTimeout }}
    system_id: {{ .Values.depServices.rds.system_id | quote }}

    # SSL证书
    ssl_on: {{ .Values.service.sslOn }}
    cert_file: {{ .Values.service.certFile }}
    key_file: {{ .Values.service.keyFile }}

    # 授权服务
    oauth_public_host: {{ .Values.depServices.hydra.publicHost | quote }}
    oauth_public_port: {{ .Values.depServices.hydra.publicPort }}
    oauth_admin_host: {{ .Values.depServices.hydra.administrativeHost | quote }}
    oauth_admin_port: {{ .Values.depServices.hydra.administrativePort }}

  mq_config.yaml: |
    {{- toYaml .Values.depServices.mq | nindent 4 }}
